### ISSUE TITLE
Could server-side naming be clearer?

### ISSUE THREAD

**Issue by rachaelcodes** [FAC-11/week-4-TAAA#47]
We're finding the names of the server-side modules a little confusing. Handlers.js contains both routers and handling functionality and Api.js contains handling functionality. Is the function of apiRequest() to make a request or to handle the response? Could backend.js have a more descriptive name?

The examples we were given used the convention server - router - handler. Obviously, we don't have to follow conventions, but it might make code easier for other people to read.

**Comment by rebecacalvoquintero** [comment]
A little note on this =):
maybe in backend.js, the name of the "comparefunction" could be changed to something that describes more what that function does?;)
