### ISSUE TITLE
Readability of ternary operators

### ISSUE THREAD

**Issue by finnhodgkin** [FAC-11/week-4-TAAA#48]
This is more of a personal opinion issue but ternary operators are often harder to read, especially when they're long and kept to one line.

Using the example from backend.js:

```js
var shrunkResults = arrayOfStrings.length <=  5 ? arrayOfStrings : arrayOfStrings.slice(0,5);
```

That goes over the 80 character soft line limit and isn't (at least for me) _instantly_ scan-able. I'm not you shouldn't use ternary operators, and this example is actually a __great__ use-case, but where possible I try to keep code clarity by adding line-breaks or just using if statements, etc:

```js   
var shrunkResults =  arrayOfStrings.length <= 5 ? 
      arrayOfStrings : 
      arrayOfStrings.slice(0, 5);
```

**Comment by absorpheus** [comment]
Function is now redundant 

#57
